### ISSUE TITLE
Questions regarding the tool

### ISSUE THREAD

**Issue by Eden0923** [wrightgs/CHARMING#1]
Hiii, my name is Eden. I have started using your tool recently both the online and script based, but I am having issues regarding two things.
1. The online - the maximum allowable codon number for this version is 350 codons but whenever an input a sequence which is close to  but less than 350 ( lets say 349,347....etc). The reply that I am getting is an error message saying  "The gateway did not receive a timely response from the upstream server or application". So, I was wondering what the threshold number is
2. The script - 
" If you would like to run CHARMING to generate 3 synonymous sequences for expression in E. coli instead of S. cerevisiae (keeping the other parameters the same), simply remove the last argument and type:

python CHARMING.py EcolTestSeq.txt 3 10 MM tutorial EcolCUB.txt"

I tried to run this line but I keep getting this message 

![github](https://user-images.githubusercontent.com/54263645/196843132-c8b3a1ea-dddd-4b8e-806d-07789f1bc68d.png)

but when I added EcolCUB.txt in the last argument, it kinda worked
"python CHARMING.py EcolTestSeq.txt 3 10 MM tutorial EcolCUB.txt EcolCUB.txt"
Just wanted to know if its ok to use this command line to run the code.

Thanks in advance.

**Comment by wrightgs** [comment]
Thank you for your inquiries!

To your first question - the 350 codons is really more of a guideline than a hard rule. The server has (I believe - I'm no longer at the institution housing it) a 60 second timeout and any process that takes longer than that will result in the timeout error. Some sequences are "easier" to harmonize than others, and when we were testing it 350 seemed to be about the correct number that could generate 3 harmonized mutants before the timeout. However, a particularly "difficult" sequence that is 330 codons long could also cause this timeout error. There was talk about updating the server to accommodate longer sequences - I'll reach out to the people maintaining it to see if that is still in the works.

To your second question - it looks like there was a bug in the script. I have updated it and the original command should now run without issue. I wouldn't recommend doing your second command, the algorithm is a little bit different when harmonizing to the origin species vs a host species, and doing the second command above could result in you just getting the original sequence output back to you.

**Comment by Eden0923** [comment]
Hii

I just saw your e-mail today ( there was a lot that I could not recognize), I am really sorry for my negligence.
Thank you so much for the correction and update.
